// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Connect(arg1:string,arg2:string):Promise<void>;

export function GetFiles():Promise<Array<models.FileInfo>>;

export function GetWatchDir():Promise<string>;

export function IsConnected():Promise<boolean>;

export function MinimizeToTray():Promise<void>;

export function SetWatchDir(arg1:string):Promise<void>;

export function SetupSystemTray():Promise<void>;

export function Shutdown():Promise<void>;
