// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['app']['App']['Connect'](arg1, arg2);
}

export function GetFiles() {
  return window['go']['app']['App']['GetFiles']();
}

export function GetWatchDir() {
  return window['go']['app']['App']['GetWatchDir']();
}

export function IsConnected() {
  return window['go']['app']['App']['IsConnected']();
}

export function MinimizeToTray() {
  return window['go']['app']['App']['MinimizeToTray']();
}

export function SetWatchDir(arg1) {
  return window['go']['app']['App']['SetWatchDir'](arg1);
}

export function SetupSystemTray() {
  return window['go']['app']['App']['SetupSystemTray']();
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}
