// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sync} from '../models';

export function GetFiles():Promise<Array<sync.FileInfo>>;

export function GetWatchDir():Promise<string>;

export function MinimizeToTray():Promise<void>;

export function SetWatchDir(arg1:string):Promise<void>;
