// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetWatchDir() {
  return window['go']['main']['App']['GetWatchDir']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}
